# Generated by Django 5.2 on 2025-05-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_alter_book_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='total_rental',
            new_name='total_retal',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('availble', 'availble'), ('sold', 'sold'), ('rental', 'rental')], max_length=50, null=True),
        ),
    ]
