# Generated by Django 5.2 on 2025-06-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_editor_alter_book_status_book_editors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='name',
        ),
        migrations.AddField(
            model_name='editor',
            name='editors',
            field=models.ManyToManyField(blank=True, to='lms_app.editor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('sold', 'sold'), ('rental', 'rental'), ('availble', 'availble')], max_length=50, null=True),
        ),
    ]
