# Generated by Django 5.2 on 2025-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_remove_editor_name_editor_editors_alter_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='editors',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('rental', 'rental'), ('availble', 'availble'), ('sold', 'sold')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
