# Generated by Django 5.2 on 2025-05-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_rename_total_rental_book_total_retal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('sold', 'sold'), ('availble', 'availble'), ('rental', 'rental')], max_length=50, null=True),
        ),
    ]
