# Generated by Django 5.2 on 2025-06-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_remove_editor_editors_remove_book_editors_delete_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status_color',
            field=models.CharField(blank=True, help_text='اختر لون الحالة', max_length=7),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('rental', 'rental'), ('sold', 'sold'), ('availble', 'availble')], max_length=50, null=True),
        ),
    ]
