# Generated by Django 5.2 on 2025-05-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_course_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('sold', 'sold'), ('availble', 'availble'), ('rental', 'rental')], max_length=50, null=True),
        ),
    ]
