# Generated by Django 5.2 on 2025-05-28 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_rename_instructor_course_name_remove_course_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_app.course'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('sold', 'sold'), ('availble', 'availble'), ('rental', 'rental')], max_length=50, null=True),
        ),
    ]
