# Generated by Django 5.2 on 2025-05-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0010_book_course_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('rental', 'rental'), ('sold', 'sold'), ('availble', 'availble')], max_length=50, null=True),
        ),
    ]
